org: stevensc
app: lite-thinking-pdf
service: lite-thinking-pdf
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  timeout: 180
  memorySize: 256

  iamRoleStatements:
    - Effect: Allow
      Action:
        - cognito-idp:AdminInitiateAuth
        - cognito-idp:AdminCreateUser
        - cognito-idp:AdminSetUserPassword
      Resource: "*"

    - Effect: Allow
      Action:
        - s3:*
      Resource: "arn:aws:s3:::lov-file-inventory"

    - Effect: "Allow"
      Action:
        - dynamodb:GetItem
        - dynamodb:Query
        - dynamodb:PutItem
        - dynamodb:Scan
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:382572906864:table/Lite-Thinking-dev"


functions:
  generatePDF:
    handler: index.generatePDF
    timeout: 180
    memorySize: 256
    events:
      - http:
          path: generatePDF
          method: post
          cors: true # <-- CORS!
          authorizer:
            name: PrivateAuthorizer
            type: COGNITO_USER_POOLS
            arn: arn:aws:cognito-idp:us-east-1:382572906864:userpool/us-east-1_3wxvIMG40
